/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package h2db;

import java.sql.SQLException;

import h2db.data.H2DBSample;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        H2DBSample h2dbSample = new H2DBSample();
        h2dbSample.initExe();

        while(true){
            try {
                Thread.sleep(100000);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }
}
